name: my first workflow

on:
  push

jobs:

  my-first-job:

    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
    
      - name: Run Trivy vulnerability scanner in repo mode
        id: scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          exit-code: '0'
          output: 'trivy-results.txt'
          severity: 'CRITICAL,HIGH'

      - name: Display Trivy scan results
        run: cat trivy-results.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-fortune:${{ github.sha }}