name: my first workflow

on:
  push

jobs:

  my-first-job:

    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
    
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH'